### ISSUE TITLE
Create :description textarea field

### ISSUE THREAD

**Issue by iteles** [dwyl/fields#20]
Moved here from https://github.com/dwyl/autoform/issues/23

For fields in my form which require more details and therefore longer inputs from my users, 
I would like to have the option to use a `textarea` instead of the default input field,
In order to improve the user experience, allowing users to see more of what they have typed.

### Use Case
This specific use case has arisen from a client project where venues (or low or no alcoholic beverages) are being listed.   
_It is my hypothesis that it is highly likely that people will copy-paste into this field rather than writing everything out themselves._

## Acceptance Criteria
+ [ ] Create `:description_plaintext_unlimited` (`String`) field for descriptions that don't need to be encrypted (there are no security concerns around this data and the intent is for it to be publicly visible)
  + [ ] `<textarea>` that will accept a string of text
  + [ ] Symbols and special characters such as `ü` must be accepted
  + [ ] Images cannot be copy-pasted into this field
  + [ ] Basic formatting of carriage returns must be retained
  + [ ] HTML to be sanitised out as per #19 
+ [ ] Clear addition to the documentation on the field, specification and use case

Notes: at this stage, the following are _not_ requirements:
+ Rich text formatting
+ Character/word limits or counts are not required at this stage (and I believe this should be a separate issue anyway)

**Comment by nelsonic** [comment]
@iteles does the **`textarea`** need to accept **`plaintext`** or **`richtext`**?
(_should it use the sanitisation function #19 to "strip" any HTML/Markdown?_)

**Comment by iteles** [comment]
For this specific use case, it only needs to accept plain text.

**Comment by nelsonic** [comment]
@iteles thanks for quick reply. I _agree_ that having a _generic_ **`<textarea>`** field is _useful_ for _automatically_ building Forms (_and we should add some acceptance criteria to this issue_).

_However_ I _also_ want to encourage everyone to define _highly_ precise/specific Fields so that a _complete beginner_ defining a schema using **`fields`** can _immediately_ see which is the most appropriate field for their use case. I know the _origin_ of this issue is a Client Project, and it would be _useful_ to get more _context_ so that others can _understand_ why the "_generic_" **`<textarea>`** is the most _appropriate_ field to be used in that _specific_ situation.

If for _example_ you were creating a "school-based (internal) social network for middle-school students" (_generic example project for illustrative purposes_), and there was a requirement for field called **`Fields.blog_post_micro`** it would _immediately_ obvious to _everyone_ on the team what data is being captured, how it needs to be validated, sanitised and stored. And then the UI/UX for _rendering_ the _view_ with appropriate formatting would also be relatively easy to define. 
If there was a _character limit_ for the post (_e.g: [280 characters](https://techcrunch.com/2017/11/07/twitter-officially-expands-its-character-count-to-280-starting-today/)_) then the UX could include a _character counter_ which would give the user (_person entering data_) a clear visual indication of their "progress" and/or "limit".

**Comment by iteles** [comment]
@nelsonic I have updated the top comment with as much information as I have at this stage.  
Is this clearer?

**Comment by nelsonic** [comment]
@iteles _amaze_! 😍

**Comment by nelsonic** [comment]
@iteles _amaze_! 😍 

Consider adding a "Docs" checklist item to the Acceptance criteria so building `Field.description` includes a _clear_ explanation of the use case so people _using_ this package know what the purpose of description is. 

Also, having _some_ sort of **character limit** on the amount of text use _useful_ for guiding users to not post an *essay*. But if your objective/use-case is a "free text" description, then perhaps a **more _specific_** field name: **`description_plaintext_unlimited`** might be more apt? 🤔

**Comment by iteles** [comment]
I thought docs (and tests) go without saying (point 3 in https://github.com/dwyl/contributing#step-2-assign-yourself-the-task-and-do-it), but I'll add them.

My objective is a completely free text field so that we can _user test_ and _see_ whether or not we need to add in the complexity of character/word counts and what those limits might be if they're needed.    
The display of this text does not break for long descriptions in the use case I have in mind.

The acceptance criteria that exists (in particular around copy-pasting of images) comes from user testing on a different project with a similar use case. The field would be this _exact_ specification but is not a description, it is a 'welcome message'.

Happy to make the name more verbose, this was just a suggestion.  
`plaintext` might be a little misleading if line break formatting is needed. Is there a better way to reference this that anyone can think of?

**Comment by nelsonic** [comment]
@iteles I'm happy for you to be the "Sponsor" on this feature and define all it's detail/acceptance criteria. I'm just _encouraging_ you to have a _super_ descriptive/specific field name that makes it immediately obvious to a **_complete_ beginner** joining a project where this field is _used_ what the field is for and what type of data it "accepts". 
(IMO) the fields in this package _should_ be "verbose" when there is _any_ chance they will be _misused_ e.g: if we have a `Fields.description` will it be used _everywhere_ "freetext" capture is required? If it's the case that we _want_ a "generic" `:description` field that's "OK", but then we need to be prepared for _beginners_ to use it in places where a more _specific_ field would be more appropriate.

**Comment by iteles** [comment]
`:description_plaintext_unlimited` 👆 

@nelsonic It will probably be useful to open an issue on ***verbose naming of fields*** in this package, with a 2 sentence description of _why_ and get this into the docs for `fields`.

**Comment by nelsonic** [comment]
@Danwhy sounds like a good plan. thanks for sharing your implementation idea. 👍

**Comment by nelsonic** [comment]
https://github.com/dwyl/fields/blob/master/lib/description_plaintext_unlimited.ex
Implemented by @Danwhy in #25 🎉
