### ISSUE TITLE
Postcode HR9 1EA invalid?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/fields#45]
Busy trying to import data and getting the following error:
![image](https://user-images.githubusercontent.com/194400/57871202-b7c53a80-7800-11e9-9b4c-0c97054703d4.png)

`HR9 1EA` invalid?

Google seems to think it's OK: 
https://www.google.com/search?q=23+Broad+Street+Ross+on+Wye

![image](https://user-images.githubusercontent.com/194400/57871368-1094d300-7801-11e9-9cb1-0faeff5b7e3a.png)

Investigating why our regex is failing this Postcode ...

**Comment by RobStallion** [comment]
The validation for this postcode failed because although it looks like a "real" postcode, it is not actually correct. However, it was not the regex that caused this to fail. 

This postcode will pass the regex but when we insert venues (in club soda) we do extra checks to make sure it is a valid postcode. We use the postcode to generate the lat long values, which are then used to display a venues location on a map. If the postcode is not valid then the other steps will fail.

In club soda we check the postcode against our cache of postcodes. If the postcode is in the cache we grab the lat-long value from their and that's it. If the postcode is not in the cache, we make an api call to https://postcodes.io/. This is our fallback option. 

If postcodes.io responds with an error we know that the postcode is actually invalid.

**Comment by nelsonic** [comment]
@RobStallion thanks for clarifying. 💡 
Closing as nothing more we can do with this. ✅
